[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"

[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
