[build]
  functions = "functions-build"
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

[[redirects]]
  from = "/bingo/*"
  to = "/bingo/index.html"
  status = 200

