[build]
  functions = "functions-build"
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "/app/*"
  to = "/app/index.html"
  status = 200

[[redirects]]
  from = "/cv2612/*"
  to = "https://cv2612.netlify.app/"
  status = 301

